title:            Zixuan Wang's site
description:      Welcome to my site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //wangzx19.github.io
#http://localhost:5000
#https://jponttuset.github.io
disqus_shortname: jponttuset

# Owner/author information
owner:
  name:           Zixuan Wang
  avatar:         #
  bio:            I am currently an undergraduate student in IIIS, Tsinghua University. 
  email:          wangzx2019012326@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  google_scholar: vNJDZyEAAAAJ
# github: Jiyuan-Tan
# Analytics and webmaster tools stuff goes here
# google_analytics: UA-52736040-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Experiences
    url: /cv/
  - title: Publications
    url: /publications/
#  - title: Photos
#    url: /photos/
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
Timezone: Asia/Shanghai
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

syntax_highlighter_opts:
  line_numbers:
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
